# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ziZKkvbWzoG8tzSysbqV5iBNpnGKPFx
"""

!pip install crewai[tools] langchain-google-genai

pip install --upgrade google-ai-generativelanguage==0.6.15

from crewai import Agent, Task, Crew, Process
from langchain_google_genai import ChatGoogleGenerativeAI

import os
os.environ["GOOGLE_API_KEY"] = "AIzaSyAxPrPcZomgTU7Nf7jqqZ4r5UJxNKKjNcg"

from crewai import LLM

# Initialize Gemini model
gemini = LLM( api_key=os.environ["GOOGLE_API_KEY"],
    model="gemini/gemini-1.5-flash",  # note the correct provider prefix
    verbose=True)

# Writer Agent: drafts the initial LinkedIn post
writer = Agent(
    role="Content Writer",
    goal="Draft an engaging LinkedIn post about Java applications in the IT field.",
    backstory="An expert writer who crafts concise, professional LinkedIn content.",
    llm=gemini,
    verbose=True
)

# Editor Agent: refines the draft
editor = Agent(
    role="Content Editor",
    goal="Refine and polish the draft to improve clarity, tone, and engagement.",
    backstory="An editor skilled in LinkedIn audience tone and professional language.",
    llm=gemini,
    verbose=True
)

# Define tasks
draft_task = Task(
    agent=writer,
    description="Write a draft LinkedIn post covering key uses of Java in IT (enterprise, cloud, AI, migration).",
    expected_output="A draft LinkedIn post (~150–250 words)."
)

edit_task = Task(
    agent=editor,
    description="Take the writer’s draft and polish it—improve flow, tone, and engagement while keeping it under 200 words.",
    expected_output="A final polished LinkedIn post.",
    context=[draft_task]
)

# Build the crew
crew = Crew(
    agents=[writer, editor],
    tasks=[draft_task, edit_task],
    process=Process.sequential,
    verbose=True
)

# Run the crew
result = crew.kickoff()

print("\n✅ Final LinkedIn Post:\n")
print(result)

